/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TIMS.invoice.view;

import TIMS.app.lib.hbm.TimsInvoice;
import TIMS.invoice.view.partial.ProductSelecter;
import java.awt.BorderLayout;

/**
 *
 * @author Nuwan Chathuranga <icechathuranga@gmail.com>
 */
public class AddItemsPanel extends javax.swing.JPanel {

    private TimsInvoice invoice;

    public TimsInvoice getInvoice() {
        return invoice;
    }

    public void setInvoice(TimsInvoice invoice) {
        this.invoice = invoice;
    }
    
    
    /**
     * Creates new form AddItemsPanel
     */
    public AddItemsPanel(TimsInvoice invoice) {
        this.invoice = invoice;
        initComponents();
        setLayout(new BorderLayout());
        add(new ProductSelecter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(640, 512));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
