package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsScreen generated by hbm2java
 */
public class TimsScreen  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String class_;
     private String url;
     private Set timsMenuItems = new HashSet(0);
     private Set timsDataGroups = new HashSet(0);
     private Set timsUserRoles = new HashSet(0);

    public TimsScreen() {
    }

    public TimsScreen(String name, String description, String class_, String url, Set timsMenuItems, Set timsDataGroups, Set timsUserRoles) {
       this.name = name;
       this.description = description;
       this.class_ = class_;
       this.url = url;
       this.timsMenuItems = timsMenuItems;
       this.timsDataGroups = timsDataGroups;
       this.timsUserRoles = timsUserRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getTimsMenuItems() {
        return this.timsMenuItems;
    }
    
    public void setTimsMenuItems(Set timsMenuItems) {
        this.timsMenuItems = timsMenuItems;
    }
    public Set getTimsDataGroups() {
        return this.timsDataGroups;
    }
    
    public void setTimsDataGroups(Set timsDataGroups) {
        this.timsDataGroups = timsDataGroups;
    }
    public Set getTimsUserRoles() {
        return this.timsUserRoles;
    }
    
    public void setTimsUserRoles(Set timsUserRoles) {
        this.timsUserRoles = timsUserRoles;
    }




}


