package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsUser generated by hbm2java
 */
public class TimsUser  implements java.io.Serializable {


     private Integer id;
     private TimsEmployee timsEmployee;
     private String userName;
     private String password;
     private Integer status;
     private Set timsUserRoles = new HashSet(0);

    public TimsUser() {
    }

    public TimsUser(TimsEmployee timsEmployee, String userName, String password, Integer status, Set timsUserRoles) {
       this.timsEmployee = timsEmployee;
       this.userName = userName;
       this.password = password;
       this.status = status;
       this.timsUserRoles = timsUserRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TimsEmployee getTimsEmployee() {
        return this.timsEmployee;
    }
    
    public void setTimsEmployee(TimsEmployee timsEmployee) {
        this.timsEmployee = timsEmployee;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public void setPassword(char[] password) {
        this.setPassword(new String(password));
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getTimsUserRoles() {
        return this.timsUserRoles;
    }
    
    public void setTimsUserRoles(Set timsUserRoles) {
        this.timsUserRoles = timsUserRoles;
    }




}


