package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsProductGroup generated by hbm2java
 */
public class TimsProductGroup  implements java.io.Serializable {


     private Integer code;
     private String name;
     private String description;
     private Set timsProducts = new HashSet(0);

    public TimsProductGroup() {
    }

    public TimsProductGroup(String name, String description, Set timsProducts) {
       this.name = name;
       this.description = description;
       this.timsProducts = timsProducts;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTimsProducts() {
        return this.timsProducts;
    }
    
    public void setTimsProducts(Set timsProducts) {
        this.timsProducts = timsProducts;
    }




}


