/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TIMS.app.template;

import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Nuwan Chathuranga <icechathuranga@gmail.com>
 */
public abstract class AbstractTimsTemplate extends javax.swing.JFrame implements TimsTemplateInterface {

    /**
     * Creates new form AbstractTimsTemplate
     */
    public AbstractTimsTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScroll = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIMS - Bit Project");

        mainScroll.setMinimumSize(new java.awt.Dimension(660, 525));
        mainScroll.setPreferredSize(new java.awt.Dimension(660, 525));

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainPanel.setMinimumSize(new java.awt.Dimension(640, 512));
        mainPanel.setPreferredSize(new java.awt.Dimension(640, 512));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        mainScroll.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(mainScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(mainScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScroll;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    @Override
    public JFrame getMainFrame() {
        return this;
    }

    @Override
    public JMenuBar getMainMenuBar() {
        return this.getJMenuBar();
    }

    @Override
    public void setMainPanel(JPanel panel) {
        this.mainPanel = panel;
    }

    @Override
    public void setMainMenuBar(JMenuBar menuBar) {
        this.setJMenuBar(menuBar);
    }

    public void render() {
        this.setVisible(true);
    }
    
    public JScrollPane getMainScrollPanel(){
        return mainScroll;
    }
}
