package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsUserRole generated by hbm2java
 */
public class TimsUserRole  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Integer status;
     private Set timsUsers = new HashSet(0);
     private Set timsScreens = new HashSet(0);
     private Set timsDataGroups = new HashSet(0);

    public TimsUserRole() {
    }

    public TimsUserRole(String name, String description, Integer status, Set timsUsers, Set timsScreens, Set timsDataGroups) {
       this.name = name;
       this.description = description;
       this.status = status;
       this.timsUsers = timsUsers;
       this.timsScreens = timsScreens;
       this.timsDataGroups = timsDataGroups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getTimsUsers() {
        return this.timsUsers;
    }
    
    public void setTimsUsers(Set timsUsers) {
        this.timsUsers = timsUsers;
    }
    public Set getTimsScreens() {
        return this.timsScreens;
    }
    
    public void setTimsScreens(Set timsScreens) {
        this.timsScreens = timsScreens;
    }
    public Set getTimsDataGroups() {
        return this.timsDataGroups;
    }
    
    public void setTimsDataGroups(Set timsDataGroups) {
        this.timsDataGroups = timsDataGroups;
    }




}


