package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsPurches generated by hbm2java
 */
public class TimsPurches  implements java.io.Serializable {


     private Integer code;
     private TimsInvoice timsInvoice;
     private TimsProduct timsProduct;
     private TimsBarnd timsBarnd;
     private Integer rate;
     private Long discount;
     private Long tax;
     private String status;
     private Integer qty;
     private Set timsRecievedGoods = new HashSet(0);

    public TimsPurches() {
    }

    public TimsPurches(TimsInvoice timsInvoice, TimsProduct timsProduct, TimsBarnd timsBarnd, Integer rate, Long discount, Long tax, String status, Integer qty, Set timsRecievedGoods) {
       this.timsInvoice = timsInvoice;
       this.timsProduct = timsProduct;
       this.timsBarnd = timsBarnd;
       this.rate = rate;
       this.discount = discount;
       this.tax = tax;
       this.status = status;
       this.qty = qty;
       this.timsRecievedGoods = timsRecievedGoods;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public TimsInvoice getTimsInvoice() {
        return this.timsInvoice;
    }
    
    public void setTimsInvoice(TimsInvoice timsInvoice) {
        this.timsInvoice = timsInvoice;
    }
    public TimsProduct getTimsProduct() {
        return this.timsProduct;
    }
    
    public void setTimsProduct(TimsProduct timsProduct) {
        this.timsProduct = timsProduct;
    }
    public TimsBarnd getTimsBarnd() {
        return this.timsBarnd;
    }
    
    public void setTimsBarnd(TimsBarnd timsBarnd) {
        this.timsBarnd = timsBarnd;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }
    public Long getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Long discount) {
        this.discount = discount;
    }
    public Long getTax() {
        return this.tax;
    }
    
    public void setTax(Long tax) {
        this.tax = tax;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Set getTimsRecievedGoods() {
        return this.timsRecievedGoods;
    }
    
    public void setTimsRecievedGoods(Set timsRecievedGoods) {
        this.timsRecievedGoods = timsRecievedGoods;
    }




}


