package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TimsRecievedGood generated by hbm2java
 */
public class TimsRecievedGood  implements java.io.Serializable {


     private Integer code;
     private TimsPurches timsPurches;
     private TimsGoodRecieveNote timsGoodRecieveNote;
     private Integer qty;
     private Date date;
     private String note;

    public TimsRecievedGood() {
    }

    public TimsRecievedGood(TimsPurches timsPurches, TimsGoodRecieveNote timsGoodRecieveNote, Integer qty, Date date, String note) {
       this.timsPurches = timsPurches;
       this.timsGoodRecieveNote = timsGoodRecieveNote;
       this.qty = qty;
       this.date = date;
       this.note = note;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public TimsPurches getTimsPurches() {
        return this.timsPurches;
    }
    
    public void setTimsPurches(TimsPurches timsPurches) {
        this.timsPurches = timsPurches;
    }
    public TimsGoodRecieveNote getTimsGoodRecieveNote() {
        return this.timsGoodRecieveNote;
    }
    
    public void setTimsGoodRecieveNote(TimsGoodRecieveNote timsGoodRecieveNote) {
        this.timsGoodRecieveNote = timsGoodRecieveNote;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


