package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsEmployee generated by hbm2java
 */
public class TimsEmployee  implements java.io.Serializable {


     private Integer id;
     private String number;
     private String firstName;
     private String lastName;
     private String otherName;
     private String pobox;
     private String street;
     private String city;
     private String mobile;
     private String telephone;
     private Set timsUsers = new HashSet(0);

    public TimsEmployee() {
    }

    public TimsEmployee(String number, String firstName, String lastName, String otherName, String pobox, String street, String city, String mobile, String telephone, Set timsUsers) {
       this.number = number;
       this.firstName = firstName;
       this.lastName = lastName;
       this.otherName = otherName;
       this.pobox = pobox;
       this.street = street;
       this.city = city;
       this.mobile = mobile;
       this.telephone = telephone;
       this.timsUsers = timsUsers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getOtherName() {
        return this.otherName;
    }
    
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }
    public String getPobox() {
        return this.pobox;
    }
    
    public void setPobox(String pobox) {
        this.pobox = pobox;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Set getTimsUsers() {
        return this.timsUsers;
    }
    
    public void setTimsUsers(Set timsUsers) {
        this.timsUsers = timsUsers;
    }




}


