package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TimsPayment generated by hbm2java
 */
public class TimsPayment  implements java.io.Serializable {


     private Integer code;
     private TimsPaymentMethod timsPaymentMethod;
     private TimsInvoice timsInvoice;
     private Long amount;
     private Date date;

    public TimsPayment() {
    }

    public TimsPayment(TimsPaymentMethod timsPaymentMethod, TimsInvoice timsInvoice, Long amount, Date date) {
       this.timsPaymentMethod = timsPaymentMethod;
       this.timsInvoice = timsInvoice;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public TimsPaymentMethod getTimsPaymentMethod() {
        return this.timsPaymentMethod;
    }
    
    public void setTimsPaymentMethod(TimsPaymentMethod timsPaymentMethod) {
        this.timsPaymentMethod = timsPaymentMethod;
    }
    public TimsInvoice getTimsInvoice() {
        return this.timsInvoice;
    }
    
    public void setTimsInvoice(TimsInvoice timsInvoice) {
        this.timsInvoice = timsInvoice;
    }
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


