package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsDataGroup generated by hbm2java
 */
public class TimsDataGroup  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Byte read;
     private Byte create;
     private Byte update;
     private Byte delete;
     private Byte self;
     private Set timsScreens = new HashSet(0);
     private Set timsUserRoles = new HashSet(0);

    public TimsDataGroup() {
    }

    public TimsDataGroup(String name, String description, Byte read, Byte create, Byte update, Byte delete, Byte self, Set timsScreens, Set timsUserRoles) {
       this.name = name;
       this.description = description;
       this.read = read;
       this.create = create;
       this.update = update;
       this.delete = delete;
       this.self = self;
       this.timsScreens = timsScreens;
       this.timsUserRoles = timsUserRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getRead() {
        return this.read;
    }
    
    public void setRead(Byte read) {
        this.read = read;
    }
    public Byte getCreate() {
        return this.create;
    }
    
    public void setCreate(Byte create) {
        this.create = create;
    }
    public Byte getUpdate() {
        return this.update;
    }
    
    public void setUpdate(Byte update) {
        this.update = update;
    }
    public Byte getDelete() {
        return this.delete;
    }
    
    public void setDelete(Byte delete) {
        this.delete = delete;
    }
    public Byte getSelf() {
        return this.self;
    }
    
    public void setSelf(Byte self) {
        this.self = self;
    }
    public Set getTimsScreens() {
        return this.timsScreens;
    }
    
    public void setTimsScreens(Set timsScreens) {
        this.timsScreens = timsScreens;
    }
    public Set getTimsUserRoles() {
        return this.timsUserRoles;
    }
    
    public void setTimsUserRoles(Set timsUserRoles) {
        this.timsUserRoles = timsUserRoles;
    }




}


