package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsSupplier generated by hbm2java
 */
public class TimsSupplier  implements java.io.Serializable {

     private Integer code;
     private String name;
     private String otherName;
     private String pobox;
     private String street;
     private String city;
     private Integer telephone;
     private Integer mobileNo;
     private Integer fax;
     private String email;
     private Set timsInvoices = new HashSet(0);

    public TimsSupplier() {
    }

    public TimsSupplier(String name, String otherName, String pobox, String street, String city, Integer telephone, Integer mobileNo, Integer fax, String email, Set timsInvoices) {
       this.name = name;
       this.otherName = otherName;
       this.pobox = pobox;
       this.street = street;
       this.city = city;
       this.telephone = telephone;
       this.mobileNo = mobileNo;
       this.fax = fax;
       this.email = email;
       this.timsInvoices = timsInvoices;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public TimsSupplier setName(String name) {
        this.name = name;
        return this;
    }
    public String getOtherName() {
        return this.otherName;
    }
    
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }
    public String getPobox() {
        return this.pobox;
    }
    
    public void setPobox(String pobox) {
        this.pobox = pobox;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }
    public Integer getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(Integer mobileNo) {
        this.mobileNo = mobileNo;
    }
    public Integer getFax() {
        return this.fax;
    }
    
    public void setFax(Integer fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTimsInvoices() {
        return this.timsInvoices;
    }
    
    public void setTimsInvoices(Set timsInvoices) {
        this.timsInvoices = timsInvoices;
    }
 
    public String getFullName(){
        return this.getName()+" "+this.getOtherName();
    }
}


