package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TimsGoodRecieveNote generated by hbm2java
 */
public class TimsGoodRecieveNote  implements java.io.Serializable {


     private Integer no;
     private TimsInvoice timsInvoice;
     private Date date;
     private String other;
     private Set timsRecievedGoods = new HashSet(0);

    public TimsGoodRecieveNote() {
    }

    public TimsGoodRecieveNote(TimsInvoice timsInvoice, Date date, String other, Set timsRecievedGoods) {
       this.timsInvoice = timsInvoice;
       this.date = date;
       this.other = other;
       this.timsRecievedGoods = timsRecievedGoods;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public TimsInvoice getTimsInvoice() {
        return this.timsInvoice;
    }
    
    public void setTimsInvoice(TimsInvoice timsInvoice) {
        this.timsInvoice = timsInvoice;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    public Set getTimsRecievedGoods() {
        return this.timsRecievedGoods;
    }
    
    public void setTimsRecievedGoods(Set timsRecievedGoods) {
        this.timsRecievedGoods = timsRecievedGoods;
    }




}


