package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TimsMenu generated by hbm2java
 */
public class TimsMenu  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set timsMenuItems = new HashSet(0);

    public TimsMenu() {
    }

    public TimsMenu(String name, String description, Set timsMenuItems) {
       this.name = name;
       this.description = description;
       this.timsMenuItems = timsMenuItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTimsMenuItems() {
        return this.timsMenuItems;
    }
    
    public void setTimsMenuItems(Set timsMenuItems) {
        this.timsMenuItems = timsMenuItems;
    }




}


