package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA



/**
 * TimsSaleReturn generated by hbm2java
 */
public class TimsSaleReturn  implements java.io.Serializable {


     private Integer code;
     private Integer timsInvoiceByInvoiceNo;
     private String timsProduct;
     private String timsBarnd;
     private String timsInvoiceByRefInvoiceNo;
     private String reason;
     private Integer qty;
     private Float rate;
     private String other;

    public TimsSaleReturn() {
    }

    public TimsSaleReturn(Integer timsInvoiceByInvoiceNo, String timsProduct, String timsBarnd, String timsInvoiceByRefInvoiceNo, String reason, Integer qty, Float rate, String other) {
       this.timsInvoiceByInvoiceNo = timsInvoiceByInvoiceNo;
       this.timsProduct = timsProduct;
       this.timsBarnd = timsBarnd;
       this.timsInvoiceByRefInvoiceNo = timsInvoiceByRefInvoiceNo;
       this.reason = reason;
       this.qty = qty;
       this.rate = rate;
       this.other = other;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Integer getTimsInvoiceByInvoiceNo() {
        return this.timsInvoiceByInvoiceNo;
    }
    
    public void setTimsInvoiceByInvoiceNo(Integer timsInvoiceByInvoiceNo) {
        this.timsInvoiceByInvoiceNo = timsInvoiceByInvoiceNo;
    }
    public String getTimsProduct() {
        return this.timsProduct;
    }
    
    public void setTimsProduct(String timsProduct) {
        this.timsProduct = timsProduct;
    }
    public String getTimsBarnd() {
        return this.timsBarnd;
    }
    
    public void setTimsBarnd(String timsBarnd) {
        this.timsBarnd = timsBarnd;
    }
    public String getTimsInvoiceByRefInvoiceNo() {
        return this.timsInvoiceByRefInvoiceNo;
    }
    
    public void setTimsInvoiceByRefInvoiceNo(String timsInvoiceByRefInvoiceNo) {
        this.timsInvoiceByRefInvoiceNo = timsInvoiceByRefInvoiceNo;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Float getRate() {
        return this.rate;
    }
    
    public void setRate(Float rate) {
        this.rate = rate;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


