package TIMS.app.lib.hbm;
// Generated May 30, 2014 10:33:11 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TimsInvoice generated by hbm2java
 */
public class TimsInvoice  implements java.io.Serializable {


     private Integer no;
     private TimsSupplier timsSupplier;
     private TimsCustomer timsCustomer;
     private Date date;
     private String type;
     private String vehicalNo;
     private Integer refInvoice;
     private String other;
     private String saleType;
     private Set timsSaleReturnsForRefInvoiceNo = new HashSet(0);
     private Set timsStockReturnsForRefInvoiceNo = new HashSet(0);
     private Set timsPayments = new HashSet(0);
     private Set timsStockReturnsForInvoiceNo = new HashSet(0);
     private Set timsSales = new HashSet(0);
     private Set timsPurcheses = new HashSet(0);
     private Set timsGoodRecieveNotes = new HashSet(0);
     private Set timsSaleReturnsForInvoiceNo = new HashSet(0);

    public TimsInvoice() {
    }

    public TimsInvoice(TimsSupplier timsSupplier, TimsCustomer timsCustomer, Date date, String type, String vehicalNo, Integer refInvoice, String other, String saleType, Set timsSaleReturnsForRefInvoiceNo, Set timsStockReturnsForRefInvoiceNo, Set timsPayments, Set timsStockReturnsForInvoiceNo, Set timsSales, Set timsPurcheses, Set timsGoodRecieveNotes, Set timsSaleReturnsForInvoiceNo) {
       this.timsSupplier = timsSupplier;
       this.timsCustomer = timsCustomer;
       this.date = date;
       this.type = type;
       this.vehicalNo = vehicalNo;
       this.refInvoice = refInvoice;
       this.other = other;
       this.saleType = saleType;
       this.timsSaleReturnsForRefInvoiceNo = timsSaleReturnsForRefInvoiceNo;
       this.timsStockReturnsForRefInvoiceNo = timsStockReturnsForRefInvoiceNo;
       this.timsPayments = timsPayments;
       this.timsStockReturnsForInvoiceNo = timsStockReturnsForInvoiceNo;
       this.timsSales = timsSales;
       this.timsPurcheses = timsPurcheses;
       this.timsGoodRecieveNotes = timsGoodRecieveNotes;
       this.timsSaleReturnsForInvoiceNo = timsSaleReturnsForInvoiceNo;
    }
   
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }
    public TimsSupplier getTimsSupplier() {
        return this.timsSupplier;
    }
    
    public void setTimsSupplier(TimsSupplier timsSupplier) {
        this.timsSupplier = timsSupplier;
    }
    public TimsCustomer getTimsCustomer() {
        return this.timsCustomer;
    }
    
    public void setTimsCustomer(TimsCustomer timsCustomer) {
        this.timsCustomer = timsCustomer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getVehicalNo() {
        return this.vehicalNo;
    }
    
    public void setVehicalNo(String vehicalNo) {
        this.vehicalNo = vehicalNo;
    }
    public Integer getRefInvoice() {
        return this.refInvoice;
    }
    
    public void setRefInvoice(Integer refInvoice) {
        this.refInvoice = refInvoice;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }
    public String getSaleType() {
        return this.saleType;
    }
    
    public void setSaleType(String saleType) {
        this.saleType = saleType;
    }
    public Set getTimsSaleReturnsForRefInvoiceNo() {
        return this.timsSaleReturnsForRefInvoiceNo;
    }
    
    public void setTimsSaleReturnsForRefInvoiceNo(Set timsSaleReturnsForRefInvoiceNo) {
        this.timsSaleReturnsForRefInvoiceNo = timsSaleReturnsForRefInvoiceNo;
    }
    public Set getTimsStockReturnsForRefInvoiceNo() {
        return this.timsStockReturnsForRefInvoiceNo;
    }
    
    public void setTimsStockReturnsForRefInvoiceNo(Set timsStockReturnsForRefInvoiceNo) {
        this.timsStockReturnsForRefInvoiceNo = timsStockReturnsForRefInvoiceNo;
    }
    public Set getTimsPayments() {
        return this.timsPayments;
    }
    
    public void setTimsPayments(Set timsPayments) {
        this.timsPayments = timsPayments;
    }
    public Set getTimsStockReturnsForInvoiceNo() {
        return this.timsStockReturnsForInvoiceNo;
    }
    
    public void setTimsStockReturnsForInvoiceNo(Set timsStockReturnsForInvoiceNo) {
        this.timsStockReturnsForInvoiceNo = timsStockReturnsForInvoiceNo;
    }
    public Set getTimsSales() {
        return this.timsSales;
    }
    
    public void setTimsSales(Set timsSales) {
        this.timsSales = timsSales;
    }
    public Set getTimsPurcheses() {
        return this.timsPurcheses;
    }
    
    public void setTimsPurcheses(Set timsPurcheses) {
        this.timsPurcheses = timsPurcheses;
    }
    public Set getTimsGoodRecieveNotes() {
        return this.timsGoodRecieveNotes;
    }
    
    public void setTimsGoodRecieveNotes(Set timsGoodRecieveNotes) {
        this.timsGoodRecieveNotes = timsGoodRecieveNotes;
    }
    public Set getTimsSaleReturnsForInvoiceNo() {
        return this.timsSaleReturnsForInvoiceNo;
    }
    
    public void setTimsSaleReturnsForInvoiceNo(Set timsSaleReturnsForInvoiceNo) {
        this.timsSaleReturnsForInvoiceNo = timsSaleReturnsForInvoiceNo;
    }




}


